### ISSUE TITLE
How to know when JSON stirng parse is completed

### ISSUE THREAD

**Issue by saikat-liftoffllc** [alemures/fast-json#11]
Is there any even like `on('end', () => {})` .. Because my i am trying to parse json array and I need to know when the parsing is done.

**Comment by saikat-liftoffllc** [comment]
Quick reply would be helpful.

**Comment by alemures** [comment]
Hi, you can wait until your write call finish `fastJson.write(data);` or you can also use an empty event, in that case, you will received the full json when the parsing is done:
```
fastJson.on('', (value) => {
  // value is the full json
});
// or using a path array
fastJson.on([], (value) => {
  // value is the full json
});
```
