### ISSUE TITLE
It's not de-serializing

### ISSUE THREAD

**Issue by iamisti** [alemures/fast-json#13]
fastjson is not deserializing at all. It's only cutting out the specific part of the json string and gives a string back as a result (the json serialized string). 
This library makes no sense if I understand it correctly how it works.

What i did:
```
const fastJson = new FastJson();

fastJson.on("data", (data: any) => {
    console.log(data);
  });

fastJson.write(mySerializedJsonString);
```

as a result I get a serialized json as a result. What am I doing wrong? I'm expecting to get the de-serialized object back.

**Comment by alemures** [comment]
Hi, you are right, fast-json is not converting JSON as string/buffer to actual Javascript objects. It only parses the JSON as string/buffer and returns the queried value in the same format string/buffer.

This tools is focused on performance and it is a convenient way to extract information from big JSON structures without the need to serialize/deserialize the whole JSON. Once you have the data or structure back from fast-json, you just need to use `JSON.parse(data)` to deserialize it and get your Javascript object.
