### ISSUE TITLE
Multiple values to return

### ISSUE THREAD

**Issue by iamisti** [alemures/fast-json#14]
How do I get multiple values out of a json string?

According to the documentation this is possible:
```
// Paths can be also an array of keys
fastJson.on(['spain', 'people', '1', 'name'], (value) => {
  console.log(['spain', 'people', '1', 'name'], '->', value);
});
```

but when i use it this way, it doesnt work:
```
// Paths can be also an array of keys
fastJson.on(['data.spain', 'something.people', 'other.name'], (value) => {
  console.log(value);
});
```

i need to substract values at the same time and i'd need to use it this way. 
But this never fires. Can you suggest me a way to do this?

**Comment by alemures** [comment]
The array notation is just a different way to represent a JSON path so, the array is just a list of keys that are join together to build a JSON path. This way `'spain.people[1].name'` is the same than `['spain', 'people', '1', 'name']` when it is used in the first argument of `FastJson#on` method. This is similar to the `path` argument in the lodash `get` function, see https://lodash.com/docs/#get.

To get multiple data from multiple keys you will have to call `FastJson#on` multiple times to setup the listeners, see the following example:

```javascript
let counter = 0;
const values = [];

fastJson.on('ireland.people[0].name', listener);
fastJson.on('ireland.people[1].name', listener);
fastJson.on('ireland.people[2].name', listener);

function listener(value) {
  counter++;
  values.push(value);

  if (counter === 3) {
    console.log('We got all the values', values);
  }
}
```
